### ISSUE TITLE
let 대신에 굳이 var을 쓰신 이유가 따로 있나요?

### ISSUE THREAD

**Issue by sungbin5304** [OtakoidTony/MessengerBotExample#6]
`KakaoCalc.js` 등등 많은 소스에서 `let` 대신 `var` 만을 주로 쓰셨는데, 이 부분에 대해서 따로 이유가 있나요?

**Comment by OtakoidTony** [comment]
딱히, 별 이유는 없습니다만, 그냥 제가 let을 잘 써보질 않아서 습관적으로 var를 쓰는 것 뿐 입니다.
